### ISSUE TITLE
Notosans Bengali has interchanged two ligatures হ্ণ হ্ন

### ISSUE THREAD

**Issue by madhavkiransodum** [notofonts/bengali#5]
## Defect Report
> In bengali, হ্ + ণ = U+09B9 U+09CD U+09A3 should be
![image](https://user-images.githubusercontent.com/16919364/96540120-728d1e00-12ba-11eb-809e-3546486d0e3a.png)
and হ্ + ন = U+09B9 U+09CD U+09A8 should be
![image](https://user-images.githubusercontent.com/16919364/96540157-92bcdd00-12ba-11eb-92a1-1cf4029547d3.png)
but the font now shows the opposite.

 

### Font 
  > Full file name, for example 'NotoSansBengali-Regular.ttf'.

Adobe Bengali, Galada and Atma fonts have got it right but others have got them wrong.

![image](https://user-images.githubusercontent.com/16919364/96540512-969d2f00-12bb-11eb-8921-1ad15ba65d58.png)

**Comment by tiroj** [comment]
The same issue was posted re. the Tiro Bangla fonts, which prompted me to revisit the question which we had referred to Bengali language experts in 2011. I caution against making this change without further research, as some important sources support the ligature mapping as it currently is in the Noto and numerous other fonts:
https://github.com/TiroTypeworks/Indigo/issues/30#issuecomment-1195690776

**Comment by simoncozens** [comment]
Based on John's additional research, I'm not planning to take any action on this for now.
