### ISSUE TITLE
Issues with displaying this "হ্যাঁ" character when using Noto sans bengali

### ISSUE THREAD

**Issue by marek-sedlak** [notofonts/bengali#9]
## Defect Report
> Noto fonts can be obtained from https://github.com/googlefonts/noto-fonts/tree/master/unhinted/otf/ (unhinted OTF) or https://github.com/googlefonts/noto-fonts/tree/master/hinted/ttf/ (hinted TTF). If you find a problem with either of these then please use this template to file a defect report. For feature requests and other matters, you can use part of the template and delete what you don't need.

### Title 
  > Issues with displaying this "হ্যাঁ" character when using Noto sans bengali

### Font 
  > Noto sans bengali

### Where the font came from, and when
  >   Site: https://fonts.google.com/noto/specimen/Noto+Sans
  >   Date: 2022-05-16 (preferred format)

### Font Version
  > * Win - but we are not sure if it's limited just to this platform

### OS name and version
  > Windows 10

### Application name and version
  > We can see the issues in most tools like INDD, Illustrator, word 
### Issue
  > When this character হ্যাঁ is used in text and Noto sans Bengali is picked as font family, it seems that the character is corrupted, I believe that the screenshot below shows the issue quite well. 

### Character data
  > Unfortunately not sure about the position of the font within the table

### Screenshot
![image](https://user-images.githubusercontent.com/105720011/168803692-a3cfa6aa-2bc6-4dc6-939f-bc1be5e67523.png)

**Comment by simoncozens** [comment]
Yes, this is happening right now! You can download full (development) versions from https://notofonts.github.io/bengali/
New releases will also include the full builds.
